name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "59 23 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Issue has become stale'
        stale-pr-message: 'Pull request has become stale'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
