# This is a basic workflow to help you get started with Actions

name: Update Angular

# Controls when the action will run.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8

      - name: Install dependencies
        run: |
          npm install
          npm i @angular/cli -g

      - name: Check For Updates
        env:
          access_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ng update | tee update-result.txt

          ls

          ng update 2>&1 | tee update-result.txt

          if [[ $(head -n 12 ./update-result.txt) = *"We analyzed your package.json, there are some packages to update:"* ]];
          then
            grep -E "^\s+[@/a-zA-Z0-9]+\s+.+->" update-result.txt | awk '{print $1}' | tee to-update.txt
            
            UPDATE_CMD=""
            for pkg in $(cat to-update.txt);
            do
              echo HERE I AM ${UPDATE_CMD} $pkg
              UPDATE_CMD="${UPDATE_CMD} $pkg"
            done
            
            ng update $UPDATE_CMD --verbose --force
          fi
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
